### ISSUE TITLE
help with your awesome

### ISSUE THREAD

**Issue by mrlinuxdude** [AllJavi/dotfiles#1]
how did you get your bar like this, i don't see it in your configs maybe i over looked something.
<a href="https://www.imagebam.com/view/MECHGII" target="_blank"><img src="https://thumbs4.imagebam.com/d5/e0/e9/MECHGII_t.png" alt="AllJavi_dotfiles.png"/></a>

I only see this in where the spotify widget is showing
https://github.com/AllJavi/dotfiles/raw/master/.config/awesome/widget/spotify-widget/spotify-widget-custom-playing.png

I really love it and want it Thank you

**Comment by AllJavi** [comment]
It's because that is how the original widget looks, the init.lua file is modified to look like I have

**Comment by mrlinuxdude** [comment]
oh OK that's already in your configs. Thanks. i'm not script er i was just trying to understand how it worked. Awesome setup
